"""
sync_actions_guidance.py — regenerate the AUTO-GUIDANCE appendix in
docs/ACTIONS_REFERENCE.md by invoking GetActionGuidance() in VBA for every
known action type. Keeps the in-app "Fix Errors" guidance and the public
markdown reference from drifting.

Source of truth = modExecuteInstructions.GetActionGuidance.
The markdown appendix is auto-generated; do not hand-edit between the
BEGIN/END AUTO-GUIDANCE markers.

Run: python tools/sync_actions_guidance.py
"""

import sys
from pathlib import Path
import win32com.client, pythoncom

REPO_ROOT = Path(__file__).resolve().parent.parent
CARRIER = REPO_ROOT / "PPT_AI_Editor.pptm"
DOC = REPO_ROOT / "docs" / "ACTIONS_REFERENCE.md"

BEGIN_MARKER = "<!-- BEGIN AUTO-GUIDANCE — regenerated by tools/sync_actions_guidance.py -->"
END_MARKER = "<!-- END AUTO-GUIDANCE -->"


def main() -> int:
    if not CARRIER.exists():
        print(f"ERROR: {CARRIER} not found.")
        return 1
    if not DOC.exists():
        print(f"ERROR: {DOC} not found.")
        return 1

    pythoncom.CoInitialize()
    app = win32com.client.Dispatch("PowerPoint.Application")
    app.Visible = True
    while app.Presentations.Count > 0:
        try:
            app.Presentations(1).Close()
        except Exception:
            break
    carrier = app.Presentations.Open(str(CARRIER))

    # Pull canonical action-type list straight from VBA.
    raw = app.Run("PPT_AI_Editor.pptm!modExecuteInstructions.GetAllActionTypes")
    types = sorted({t.strip() for t in raw.split(",") if t.strip()})
    print(f"Pulled {len(types)} canonical action types from GetAllActionTypes.")

    rows = []
    for t in types:
        guide = app.Run(
            "PPT_AI_Editor.pptm!modExecuteInstructions.GetActionGuidance", t
        )
        rows.append((t, guide))

    carrier.Close()

    # Build the appendix markdown.
    body = [
        BEGIN_MARKER,
        "",
        "## Appendix: canonical signature for every action",
        "",
        "This appendix is auto-extracted from "
        "`modExecuteInstructions.GetActionGuidance` — the same function that "
        "powers the **Fix Errors** button on the Execute form. Both surfaces "
        "stay in sync via `tools/sync_actions_guidance.py`.",
        "",
        "If a new action is added to the dispatcher, update GetActionGuidance "
        "and GetAllActionTypes, then re-run the sync script.",
        "",
        f"**Action types covered: {len(types)}.**",
        "",
    ]
    for action_type, guide in rows:
        body.append(f"### `{action_type}`")
        body.append("")
        body.append("```")
        # Strip leading whitespace consistently; guidance lines start with "  "
        for line in str(guide).splitlines():
            body.append(line.rstrip())
        body.append("```")
        body.append("")
    body.append(END_MARKER)
    new_appendix = "\n".join(body) + "\n"

    # Replace existing appendix (if any) or append at end.
    current = DOC.read_text(encoding="utf-8")
    if BEGIN_MARKER in current and END_MARKER in current:
        before = current.split(BEGIN_MARKER)[0]
        after = current.split(END_MARKER)[1]
        # Strip leading whitespace from `after` since new_appendix already
        # ends with a single newline. Keeps the result idempotent (re-running
        # the script produces byte-identical output).
        after = after.lstrip("\n")
        updated = before + new_appendix + ("\n" + after if after else "")
        if not updated.endswith("\n"):
            updated += "\n"
    else:
        # First-time install: append at end with separator.
        sep = "" if current.endswith("\n") else "\n"
        updated = current + sep + "\n---\n\n" + new_appendix

    if updated == current:
        print("ACTIONS_REFERENCE.md already in sync — no changes.")
        return 0

    DOC.write_text(updated, encoding="utf-8")
    new_size = len(updated)
    old_size = len(current)
    delta = new_size - old_size
    print(f"Wrote {DOC} ({old_size:,} -> {new_size:,} chars, "
          f"{'+' if delta >= 0 else ''}{delta:,}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
